import { Client } from '@modelcontextprotocol/sdk/client/index.js';
import { StdioClientTransport } from '@modelcontextprotocol/sdk/client/stdio.js';
const transport = new StdioClientTransport({ command: 'node', args: ['dist/index.js'] });
const client = new Client({ name: 'ec-mcp-smoke', version: '0.1.0' });
await client.connect(transport);
const tools = await client.listTools();
console.log('tools=' + tools.tools.map(tool => tool.name).join(','));
const search = await client.callTool({ name: 'mercari_search', arguments: { keyword: 'ポケモン', limit: 3 } });
console.log('search_is_error=' + Boolean(search.isError));
console.log('search_source_matches=' + /"source"\s*:\s*"(api|html)"/.test(String(search.content?.[0]?.text ?? '')));
const categories = await client.callTool({ name: 'mercari_get_categories', arguments: { keyword: 'ポケモン' } });
console.log('categories_is_error=' + Boolean(categories.isError));
console.log('categories_prefix=' + String(categories.content?.[0]?.text ?? '').slice(0, 400));
const detail = await client.callTool({ name: 'mercari_get_item', arguments: { item: 'm48814528195' } });
console.log('detail_name_ok=' + /"name"\s*:\s*"[^"]{2,}"/.test(String(detail.content?.[0]?.text ?? '')));
await client.close();
process.exit(0);
